name: CI/CD Pipeline

on: [push]

env:
    EMAIL: ${{ secrets.EMAIL }}
    MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
    MYSQL_USER: ${{ secrets.MYSQL_USER }}
    REDIS_HOST: ${{ secrets.REDIS_HOST }}
    REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    REDIS_PORT: ${{ secrets.REDIS_PORT }}
    REDIS_PREFIX: ${{ secrets.REDIS_PREFIX }}
    PORT: ${{ secrets.PORT }}
    REDIS_PORT: ${{ secrets.REDIS_PORT }}
    MYSQL_PORT: ${{ secrets.MYSQL_PORT }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18'
    - name: Install dependencies
      run: npm install
    - name: Run docker images
      run: docker-compose up -d  
    - name: Run api
      run: yarn dev
    - name: Run tests
      run: yarn test
      

  # build:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build
  #     run: npm run build
  #   - name: Archive production artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: dist
  #       path: dist/

  # notify:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Send email
  #     run: node send_email.js
